---
title: "power analysis"
author: "author"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(lme4)
library(lmerTest)
library(multcomp) # not available for this version of R
library(stringr)
library(textstem)
library(tidyverse)
library(kableExtra)
library(ggrepel)
library(lme4)
library(simr)
library(tidyverse)
library(afex)     # for ANOVA with repeated measures
library(emmeans)  # for post-hoc comparisons
library(effectsize)
library(pwr)


theme_set(theme_bw())

cbPalette <- c("#56B4E9", "#D55E00", "#009E73","#999999", "#E69F00")
this.dir <- dirname(rstudioapi::getSourceEditorContext()$path)
setwd(this.dir)
source("../../../helpers.R")

# v1 <- read_csv("../../01_verbs/exploratory_all_data/data/processed.csv")
# v1["Category"] <- "Verbs"

d <- read_csv("../../../00_pilot/01_v2a/data/processed.csv")
d <-d %>% mutate(WordPair = paste(Word1,Word2,sep="-"))
names(d)
View(d)
length(unique(d$ID.Ibex))
```

```{r}
pilot_data <- d %>% 
  filter(!FeatureMatch %in% c("SelfPair"))

pilot_data$FeatureMatch <- factor(pilot_data$FeatureMatch)
pilot_data$WordPair <- factor(pilot_data$WordPair)

# Fit to pilot data (example model)
pilot_model <- lmer(Response ~ FeatureMatch + (1|WordPair) + (1+FeatureMatch|ID.Ibex), data = pilot_data)
summary(pilot_model)



# Extend the number of subjects
model_ext <- extend(pilot_model, along = "ID.Ibex", n = 40)  # try 40 subjects, or as needed

# Power simulation (e.g. for detecting effect of FeatureMatch)
result <- powerSim(model_ext, nsim = 200)
summary(result)
#   successes trials mean     lower     upper
# 1        50    100  0.5 0.3983211 0.6016789

# Power curve across a range of subject counts
pc <- powerCurve(model_ext, fixed("FeatureMatch"), along = "ID.Ibex", nsim = 100)
# plot(pc)
summary(pc)

pc_summary <- summary(pc)

plot(
  pc_summary$nlevels,
  pc_summary$mean,
  type = "b",
  ylim = c(0, 1),
  xlab = "Number of participants",
  ylab = "Power",
  main = "Power Curve for FeatureMatch"
)

abline(h = 0.80, lty = 2)

```

```{r}
pc_summary <- summary(pc)

ggplot(pc_summary, aes(x = nlevels, y = mean)) +
  geom_line() +
  geom_point() +
  geom_errorbar(
    aes(ymin = lower, ymax = upper),
    width = 2
  ) +
  geom_hline(
    yintercept = 0.80,
    linetype = "dashed"
  ) +
  labs(
    x = "Number of participants",
    y = "Power",
    title = "Power Curve for FeatureMatch"
  ) +
  theme_classic()
```


