---
title: "Everything: Similarity Judgment"
author: "author"
date: "`r Sys.Date()`"
output: html_document
---
  
```{r setup, include=FALSE, warning=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(lme4)
library(lmerTest)
library(multcomp) # not available for this version of R
library(stringr)
library(textstem)
library(tidyverse)
library(kableExtra)
theme_set(theme_bw())
library(ggrepel)
cbPalette <- c("#56B4E9", "#D55E00", "#009E73","#999999", "#E69F00")
this.dir <- dirname(rstudioapi::getSourceEditorContext()$path)
setwd(this.dir)
source("../../../helpers.R")

# v1 <- read_csv("../../01_verbs/exploratory_all_data/data/processed.csv")
# v1["Category"] <- "Verbs"

v <- read_csv("../../04_v1/data/processed.csv")
v["Category"] <- "Verbs"
v["Experiment"] <- "Ex1a: Conc-Abs (Verbs)"
v["Conceptual"] <- "Conc-Abs"

n <- read_csv("../../05_n1/data/processed.csv")
n["Category"] <- "Nouns"
n["Experiment"] <- "Ex1b: Conc-Abs (Nouns)"
n["Conceptual"] <- "Conc-Abs"

a <- read_csv("../../06_a1/data/processed.csv")
a["Category"] <- "Adjs"
a["Experiment"] <- "Ex1c: Conc-Abs (Adjs)"
a["Conceptual"] <- "Conc-Abs"

a2 <- read_csv("../../07_a2/data/processed.csv")
a2["Category"] <- "Adjs"
a2["Experiment"] <- "Ex2b: Phys-Soc (Adjs)"
a2["Conceptual"] <- "Phys-Soc/Psych"


v2 <- read_csv("../../01_v2/data/processed.csv")
v2["Category"] <- "Verbs"
v2["Experiment"] <- "Ex2a: Phys-Psyc (Verbs)"
v2["Conceptual"] <- "Phys-Soc/Psych"


n2 <- read_csv("../../02_n2/data/processed.csv")
n2["Category"] <- "Nouns"
n2["Experiment"] <- "Ex3: Animacy (Nouns)"
n2["Conceptual"] <- "Animacy"

s <- read_csv("../../03_s/data/processed.csv")
s["Experiment"] <- "Ex4: Syntactic (N v. V)"
s["Conceptual"] <- "Syntactic"

d <- bind_rows(v,n,a,a2,v2,n2,s)
nrow(d)
names(d)
d$FeatureMatch <- as.factor(d$FeatureMatch)
d$FeatureMatch <- recode(d$FeatureMatch, ConceptualMatchingOnly = 'TruthCondMatchingOnly')

length(unique(d$ID.Ibex))/7


# 
sub <- d[,c("WordPair","ID.Ibex","Experiment","Response","Valence","Conceptual","FeatureMatch")]
names(sub)[names(sub) == 'ID.Ibex'] <- 'ID.true'
sub$ExperimentType <- "Similarity"
```

# Exclusions

```{r}
# Compute group-level means and SDs per Experiment × FeatureMatch
group_stats <- d %>%
  filter(FeatureMatch %in% c("DissimilarControl", "SimilarControl")) %>%
  group_by(Experiment, FeatureMatch) %>%
  summarize(
    group_mean = mean(Response, na.rm = TRUE),
    group_sd   = sd(Response, na.rm = TRUE),
    .groups = "drop"
  )

# Compute participant-level means
participant_means <- d %>%
  filter(FeatureMatch %in% c("DissimilarControl", "SimilarControl")) %>%
  group_by(Experiment, ID.Ibex, FeatureMatch) %>%
  summarize(
    MeanPropSimilar = mean(Response, na.rm = TRUE),
    .groups = "drop"
  )

# Join group means/SDs to participant means
merged <- participant_means %>%
  left_join(group_stats, by = c("Experiment", "FeatureMatch"))

# Identify participants to exclude
to_exclude_justright <- merged %>%
  filter(
    (FeatureMatch == "DissimilarControl" & MeanPropSimilar > (group_mean + group_sd)) |
    (FeatureMatch == "SimilarControl"    & MeanPropSimilar < (group_mean - group_sd))
  ) %>%
  pull(ID.Ibex) %>%
  unique()

# Check exclusion counts
print(length(to_exclude_justright))
length(unique(d$ID.Ibex))
length(to_exclude_justright) / length(unique(d$ID.Ibex))
# Final n = 299
length(unique(d$ID.Ibex)) - length(to_exclude_justright)

```


```{r}
final <- d %>% 
  filter(!ID.Ibex %in% to_exclude_justright) 
final$Conceptual = as.factor(final$Conceptual)
final$Conceptual <- relevel(final$Conceptual, ref = "Animacy")
# final$Task <- ifelse(final$Task == "Valence", "Valence", "Conceptual")
# final$Task <- factor(final$Task, levels = c("Conceptual","Valence"))
# write.csv(final,"../data/sim_task.csv")
```


```{r}
agr <- d %>% 
  filter(!ID.Ibex %in% to_exclude_justright) %>% 
  group_by(Experiment, FeatureMatch) %>% 
  reframe(MeanPropSimilar = mean(Response), 
          SD = sd(Response))

print(agr)
```


```{r}
agr <-d %>% 
  filter(!ID.Ibex %in% to_exclude_justright) %>% 
  group_by(Experiment) %>% 
  reframe(MeanPropSimilar = mean(Response), 
          CILow = ci.low(Response), 
          CIHigh = ci.high(Response)) %>%
  mutate(YMin = MeanPropSimilar - CILow, 
         YMax = MeanPropSimilar + CIHigh)
# write.csv(agr,"../data/similarity_agg.csv")

agr <- d %>% 
  filter(!ID.Ibex %in% to_exclude_justright)
# write.csv(agr,"../data/similarity_raw.csv")
```


# Wide Graph
```{r}

agr <- d %>% 
  filter(!ID.Ibex %in% to_exclude_justright) %>% 
  group_by(Experiment,FeatureMatch) %>% 
  reframe(MeanPropSimilar = mean(Response), 
          CILow = ci.low(Response), 
          CIHigh = ci.high(Response)) %>%
  mutate(YMin = MeanPropSimilar - CILow, 
         YMax = MeanPropSimilar + CIHigh)
# View(agr)

good_colors <- c(
  "ValenceMatchingOnly" = "#00BFC4",
  "TruthCondMatchingOnly" = "#F8766D",
  "MaxMismatch" = adjustcolor("#F8766D", alpha.f = 0.4),  # lighter via alpha
  "MaxMatch" = adjustcolor("#00BFC4", alpha.f = 0.4),  # lighter via alpha
  "DissimilarControl" = "#818589",
  "SimilarControl" = "#D3D3D3"
)

# Set desired order of legend labels
feature_levels <- c(
  "DissimilarControl",
  "MaxMismatch",
  "TruthCondMatchingOnly",
  "ValenceMatchingOnly",
  "MaxMatch",
  "SimilarControl"
)

# Reorder the factor before plotting
agr <- agr %>%
  mutate(FeatureMatch = factor(FeatureMatch, levels = feature_levels))

dodge = position_dodge(.9)
ggplot(data=agr, aes(x=FeatureMatch,y=MeanPropSimilar, fill=FeatureMatch)) +
  geom_bar(position=dodge,stat="identity") + 
  geom_errorbar(aes(ymin=YMin,ymax=YMax),width=.25,position=position_dodge(0.9)) +
  facet_wrap(
      ~Experiment,
      ncol=4,
      labeller=label_wrap_gen(width=16)
      ) +
  scale_fill_manual(values = good_colors) +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        text = element_text(family = "Helvetica"),
        axis.title.y = element_text(size = 16),     # y-axis title
        axis.text.y  = element_text(size = 12),     # y-axis ticks
        
        strip.text= element_text(size = 10)    # facet labels
        # legend.position = "none"# legend labels
      )

# ggsave("../graphs/simex-wide.pdf", width = 8, height = 4)
# ggsave("../graphs/simex-wide.jpg", width = 8, height = 3)

# ggsave("../graphs/simex-legend.pdf", width = 7, height = 8)

```

# Long Graph

```{r}

agr <- d %>% 
  filter(!ID.Ibex %in% to_exclude_justright) %>% 
  group_by(Experiment,FeatureMatch) %>% 
  reframe(MeanPropSimilar = mean(Response), 
          CILow = ci.low(Response), 
          CIHigh = ci.high(Response)) %>%
  mutate(YMin = MeanPropSimilar - CILow, 
         YMax = MeanPropSimilar + CIHigh)
# View(agr)

good_colors <- c(
  "ValenceMatchingOnly" = "#00BFC4",
  "TruthCondMatchingOnly" = "#F8766D",
  "MaxMismatch" = adjustcolor("#F8766D", alpha.f = 0.4),  # lighter via alpha
  "MaxMatch" = adjustcolor("#00BFC4", alpha.f = 0.4),  # lighter via alpha
  "DissimilarControl" = "#818589",
  "SimilarControl" = "#D3D3D3"
)

# Set desired order of legend labels
feature_levels <- c(
  "DissimilarControl",
  "MaxMismatch",
  "TruthCondMatchingOnly",
  "ValenceMatchingOnly",
  "MaxMatch",
  "SimilarControl"
)

# Reorder the factor before plotting
agr <- agr %>%
  mutate(FeatureMatch = factor(FeatureMatch, levels = feature_levels))


dodge = position_dodge(.9)
ggplot(data=agr, aes(x=FeatureMatch,y=MeanPropSimilar, fill=FeatureMatch)) +
  geom_bar(position=dodge,stat="identity") + 
  geom_errorbar(aes(ymin=YMin,ymax=YMax),width=.25,position=position_dodge(0.9)) +
  facet_wrap(
      ~Experiment,
      ncol=2,
      labeller=label_wrap_gen(width=16)
      ) +
  scale_fill_manual(values = good_colors) +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        # text = element_text(family = "Helvetica"),
        axis.title.y = element_text(size = 16),     # y-axis title
        axis.text.y  = element_text(size = 12),     # y-axis ticks
        
        strip.text= element_text(size = 10)    # facet labels
        # legend.position = "none"# legend labels
      )

# ggsave("../graphs/simex-wide.pdf", width = 6, height = 3)
# ggsave("../graphs/simex-long-legend.jpeg", width = 7, height = 7)

```


# Violin Plot
```{r}

# Reorder factor and filter participants
d_plot <- d %>%
  filter(!ID.Ibex %in% to_exclude_justright) %>%
  mutate(
    FeatureMatch = factor(FeatureMatch, levels = feature_levels)
  )

ggplot(d_plot, aes(x = FeatureMatch, y = Response, fill = FeatureMatch)) +
  geom_violin(trim = TRUE, alpha = 0.7) +
  stat_summary(
    fun = mean,
    geom = "point",
    shape = 21,
    size = 2,
    color = "black",
    fill = "white",
    position = position_dodge(width = 0.9)
  ) +
  stat_summary(
    fun.data = mean_cl_normal,
    geom = "errorbar",
    width = 0.2,
    color = "black",
    position = position_dodge(width = 0.9)
  ) +
  facet_wrap(
    ~Experiment,
    ncol = 2,
    labeller = label_wrap_gen(width = 16)
  ) +
  scale_fill_manual(values = good_colors) +
  labs(
    y = "Mean proportion similar",
    x = NULL
  ) +
  theme_minimal(base_size = 14) +
  theme(
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    strip.text = element_text(size = 10),
    axis.title.y = element_text(size = 16),
    axis.text.y = element_text(size = 12)
  )

```


# ARE THERE DIFFERENCES WRT FOIL?

```{r}

# df.outliers.removed$Conceptual = as.factor(df.outliers.removed$Conceptual)
# df.outliers.removed$Conceptual <- relevel(df.outliers.removed$Conceptual, ref = "Animacy")
# 
# names(d)
# dcen <- d %>% 
#     filter(!ID.Ibex %in% to_exclude_justright) %>% 
#   mutate(Task = ifelse(Task == "Valence", "Valence", "TruthCond"),
#           Task = factor(Task, levels = c("Valence", "TruthCond"))) %>% 
#   mutate(Word = as.factor(Word),
#          ID.true = as.factor(ID.true),
#          Task = as.factor(Task),
#          Conceptual = as.factor(Conceptual),
#          cTask = as.numeric(Task)-mean(as.numeric(Task)))
# 
# model <- lmer(LogReactionTime ~ cTask * Conceptual + (1 + cTask | ID.true), data = dcen)
# 
# summary(model)

```



```{r}
dcen <- d %>% 
  filter(!ID.Ibex %in% to_exclude_justright) %>% 
  filter(FeatureMatch %in% c("TruthCondMatchingOnly","ValenceMatchingOnly")) %>% 
  mutate(WordPair = as.factor(WordPair),
         ID.Ibex = as.factor(ID.Ibex),
         FeatureMatch = as.factor(FeatureMatch),
         Experiment = as.factor(Experiment),
        cResponse = as.numeric(Response)-mean(as.numeric(Response)),
        cFeatureMatch = as.numeric(FeatureMatch)-mean(as.numeric(FeatureMatch)))

m <- lmer(cResponse ~ cFeatureMatch*Experiment + (1|WordPair) + (1+cFeatureMatch|ID.Ibex), data = dcen)
summary(m)
```

```{r}
dval <- d %>% 
  filter(!ID.Ibex %in% to_exclude_justright) %>% 
  filter(FeatureMatch %in% c("ValenceMatchingOnly")) %>% 
  mutate(WordPair = as.factor(WordPair),
         ID.Ibex = as.factor(ID.Ibex),
         FeatureMatch = as.factor(FeatureMatch),
         Experiment = as.factor(Experiment),
        cResponse = as.numeric(Response)-mean(as.numeric(Response)))

m <- lmer(cResponse ~ Experiment + (1|WordPair) + (1|ID.Ibex), data = dval)
summary(m)
```

