---
title: "Similarity Judgment Task Graphs"
author: "morgan moyer"
date: "`r Sys.Date()`"
output: html_document
---


```{r setup, include=FALSE, warning=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(lme4)
library(lmerTest)
library(multcomp) # not available for this version of R
library(stringr)
library(textstem)
library(sciplot)
library(tidyverse)
theme_set(theme_bw())
cbPalette <- c("#56B4E9", "#D55E00", "#009E73","#999999", "#E69F00")
this.dir <- dirname(rstudioapi::getSourceEditorContext()$path)
setwd(this.dir)
source("../../../helpers.R")

d <- read.csv("../data/processed.csv")


d["WordPair"] <- paste(d$Word1,d$Word2,sep="-")

```


## Summary Stats
```{r}
agr <- d %>% 
  group_by(FeatureMatch) %>% 
  summarize(MeanPropSimilar = mean(Response),
            SD = sd(Response))
print(agr)
```

```{r}
ggplot(agr, aes(Response,fill=FeatureMatch)) +
  geom_density(alpha = .5)
  # facet_wrap(~FeatureMatch)

ggplot(agr, aes(Response,fill=FeatureMatch)) +
  geom_density(alpha = .5) +
  facet_wrap(~FeatureMatch)
```

```{r}

agr <- d %>% 
  group_by(FeatureMatch) %>% 
  reframe(MeanPropSimilar = mean(Response), 
          CILow = ci.low(Response), 
          CIHigh = ci.high(Response)) %>%
  mutate(YMin = MeanPropSimilar - CILow, 
         YMax = MeanPropSimilar + CIHigh)


dodge = position_dodge(.9)
ggplot(data=val, aes(x=reorder(Word,PropPositive),y=PropPositive,fill=Valence)) +
  geom_bar(position=dodge,stat="identity",color = "black") +
  geom_errorbar(aes(ymin=YMin,ymax=YMax),width=.25,position=position_dodge(0.9)) +
  scale_fill_manual(values = valence_colors) +
  ylim(0,1) +
  labs(x = "Word") +
  # theme(axis.text.x = element_text(angle = 45, hjust = 1))

  theme(
    legend.position = "top",
    legend.direction = "horizontal", 
    axis.text.x = element_text(angle = 90, hjust  = 1))
```


```{r}
agr <- d %>% 
  group_by(FeatureMatch) %>% 
  reframe(MeanPropSimilar = mean(Response), 
          CILow = ci.low(Response), 
          CIHigh = ci.high(Response)) %>%
  mutate(YMin = MeanPropSimilar - CILow, 
         YMax = MeanPropSimilar + CIHigh)
# View(agr)

dodge = position_dodge(.9)
ggplot(data=agr, aes(x=reorder(FeatureMatch,MeanPropSimilar),y=MeanPropSimilar, fill=FeatureMatch)) +
  geom_bar(position=dodge,stat="identity") + 
  geom_errorbar(aes(ymin=YMin,ymax=YMax),width=.25,position=position_dodge(0.9)) +
  theme(axis.text.x = element_text(angle = 10, hjust = 1))


```


# Exclusions

## Summary Stats
```{r}
agr <- d %>% 
  group_by(FeatureMatch) %>% 
  summarize(MeanPropSimilar = mean(Response),
            SD = sd(Response))
print(agr)
```

## Controls
```{r}
controls <- d %>% 
  filter(FeatureMatch %in% c("DissimilarControl","SimilarControl")) %>% 
  group_by(ID.Ibex,FeatureMatch) %>% 
  summarize(MeanPropSimilar = mean(Response),
            SD = sd(Response))

summary(controls$MeanPropSimilar)

ggplot(controls, aes(MeanPropSimilar,fill=FeatureMatch)) +
  geom_density(alpha = .5)
```

```{r}
# Compute group summaries
controls <- d %>% 
  filter(FeatureMatch %in% c("DissimilarControl", "SimilarControl")) %>% 
  group_by(ID.Ibex, FeatureMatch) %>% 
  summarize(
    MeanPropSimilar = mean(Response, na.rm = TRUE),
    SD = sd(Response, na.rm = TRUE),
    .groups = "drop"
  )

# Compute summary stats per FeatureMatch for annotations
summary_stats <- controls %>%
  group_by(FeatureMatch) %>%
  summarize(
    mean = mean(MeanPropSimilar),
    sd = sd(MeanPropSimilar),
    .groups = "drop"
  )

# Density plot with summary stats overlaid
ggplot(controls, aes(x = MeanPropSimilar, fill = FeatureMatch)) +
  geom_density(alpha = 0.5) +
  geom_vline(
    data = summary_stats,
    aes(xintercept = mean, color = FeatureMatch),
    linetype = "dashed",
    size = 1
  ) +
  geom_text(
    data = summary_stats,
    aes(
      x = mean,
      y = 0,
      label = sprintf("Mean = %.2f\nSD = %.2f", mean, sd),
      color = FeatureMatch
    ),
    vjust = -1,
    hjust = 0.5,
    size = 3.5,
    show.legend = FALSE
  ) +
  labs(
    title = "Density of MeanPropSimilar by FeatureMatch",
    x = "MeanPropSimilar",
    y = "Density"
  ) +
  theme_minimal()

```


```{r}
# First, get group means for each FeatureMatch
group_means <- d %>%
  filter(FeatureMatch %in% c("DissimilarControl","SimilarControl")) %>% 
  group_by(FeatureMatch) %>%
  summarize(group_mean = mean(Response, na.rm = TRUE))

# Extract the two group means
mean_dissimilar <- group_means %>% filter(FeatureMatch == "DissimilarControl") %>% pull(group_mean)
mean_similar <- group_means %>% filter(FeatureMatch == "SimilarControl") %>% pull(group_mean)

# Too Many
to_exclude_conservative <- controls %>%
  filter(
    (FeatureMatch == "DissimilarControl" & MeanPropSimilar > mean_dissimilar) |
    (FeatureMatch == "SimilarControl"   & MeanPropSimilar < mean_similar)
  ) %>%
  pull(ID.Ibex) %>%
  unique()
length(to_exclude_conservative)/length(unique(d$ID.Ibex))

# Not enough
to_exclude_loose <- controls %>%
  filter(
    (FeatureMatch == "DissimilarControl" & MeanPropSimilar > mean_dissimilar) &
    (FeatureMatch == "SimilarControl"   & MeanPropSimilar < mean_similar)
  ) %>%
  pull(ID.Ibex) %>%
  unique()
length(to_exclude_loose)/length(unique(d$ID.Ibex))

# JUST RIGHT
# Remove anything lower than mean - 1sd for Similar control
# REmove anything high than mean + 1sd for Dissimilar Control
group_sd <- d %>%
  filter(FeatureMatch %in% c("DissimilarControl","SimilarControl")) %>% 
  group_by(FeatureMatch) %>%
  summarize(group_sd = sd(Response, na.rm = TRUE))

sd_dissimilar <- group_sd %>% filter(FeatureMatch == "DissimilarControl") %>% pull(group_sd)
sd_similar <- group_sd %>% filter(FeatureMatch == "SimilarControl") %>% pull(group_sd)

to_exclude_justright <- d %>%
  group_by(ID.Ibex,FeatureMatch) %>% 
  summarize(MeanPropSimilar = mean(Response)) %>% 
  filter(
    (FeatureMatch == "DissimilarControl" & MeanPropSimilar > (mean_dissimilar+sd_dissimilar)) |
    (FeatureMatch == "SimilarControl"   & MeanPropSimilar < (mean_similar-sd_similar))
  ) %>%
  pull(ID.Ibex) %>%
  unique()

length(to_exclude_justright)
length(to_exclude_justright)/length(unique(d$ID.Ibex))


```


```{r}

agr <- d %>% 
  filter(!ID.Ibex %in% to_exclude_justright) %>% 
  group_by(FeatureMatch) %>% 
  reframe(MeanPropSimilar = mean(Response), 
          CILow = ci.low(Response), 
          CIHigh = ci.high(Response)) %>%
  mutate(YMin = MeanPropSimilar - CILow, 
         YMax = MeanPropSimilar + CIHigh)
# View(agr)

good_colors <- c(
  "ValenceMatchingOnly" = "#00BFC4",
  "ConceptualMatchingOnly" = "#F8766D",
  "MaxMismatch" = adjustcolor("#F8766D", alpha.f = 0.4),  # lighter via alpha
  "MaxMatch" = adjustcolor("#00BFC4", alpha.f = 0.4),  # lighter via alpha
  "DissimilarControl" = "#999999",
  "SimilarControl" = "#999999"
)


dodge = position_dodge(.9)
ggplot(data=agr, aes(x=reorder(FeatureMatch,MeanPropSimilar),y=MeanPropSimilar, fill=FeatureMatch)) +
  geom_bar(position=dodge,stat="identity") + 
  geom_errorbar(aes(ymin=YMin,ymax=YMax),width=.25,position=position_dodge(0.9)) +
  # facet_wrap(
  #     ~Experiment,
  #     ncol=4,
  #     labeller=label_wrap_gen(width=16)
  #     ) +
  scale_fill_manual(values = good_colors) +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        text = element_text(family = "Helvetica"),
        axis.title.y = element_text(size = 16),     # y-axis title
        axis.text.y  = element_text(size = 12),     # y-axis ticks
        
        strip.text= element_text(size = 10)    # facet labels
        # legend.position = "none"# legend labels
      )

# ggsave("../graphs/simex-wide.pdf", width = 6, height = 3)
# ggsave("../graphs/simex-legend.pdf", width = 7, height = 8)

```