---
title: "Valance Asymmetries"
author: "morgan moyer"
date: "`r Sys.Date()`"
output: html_document
---


```{r setup, include=FALSE, warning=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(lme4)
library(lmerTest)
library(multcomp) # not available for this version of R
library(stringr)
library(textstem)
library(tidyverse)
library(kableExtra)
library(emmeans)
library(BayesFactor)
library(ggrepel)
theme_set(theme_bw())
cbPalette <- c("#56B4E9", "#D55E00", "#009E73","#999999", "#E69F00")
this.dir <- dirname(rstudioapi::getSourceEditorContext()$path)
setwd(this.dir)
source("../../helpers.R")

sc <- read_csv("../data/categorization.csv")  
names(sc)[names(sc) == 'Experiment'] <- 'ConceptualFoil'
sj <- read_csv("../data/similarity.csv")
names(sj)[names(sj) == 'Experiment'] <- 'ConceptualFoil'
names(sj)[names(sj) == 'Response'] <- 'SimilarityRating'

```

# Speeded Categorization Experiments

## Preprocessing
```{r}
sc <- sc %>% 
  separate(col = ConcValCombo, into = c("Conceptual", "Valence"), sep = "\\-")

```


```{r}
agr <- sc %>% 
  group_by(ConceptualFoil,Task,Valence) %>% 
  summarize(MeanRT = mean(ReactionTime),
            SD = sd(ReactionTime),
            MeanLogRT = mean(LogReactionTime))
print(agr)
```

```{r}

```



# Total RT with median and mode stats



## horizontal format
```{r}
agr <- sc %>%
    group_by(Valence,Task,Word) %>%
    summarize(MeanReactionTime = mean(LogReactionTime), 
              CILow = ci.low(LogReactionTime), 
              CIHigh = ci.high(ReactionTime)) %>%
    mutate(YMin = MeanReactionTime - CILow, 
           YMax = MeanReactionTime + CIHigh)

agr$Task <- ifelse(agr$Task == "Valence", "Valence", "Conceptual")
agr$Task <- factor(agr$Task, levels = c("Conceptual","Valence"))

# Set dodge width to match violin grouping
dodge_width <- 0.9

ggplot(agr, aes(x = Task, y = MeanReactionTime, fill = Valence)) + 
  geom_violin(trim = FALSE, alpha = 0.4, position = position_dodge(width = dodge_width)) +

  # Add mean point with matching dodge
  stat_summary(fun = mean,
               geom = "point",
               shape = 23,
               size = 2,
               position = position_dodge(width = dodge_width)) +
  
  stat_summary(fun = median,
                geom = "crossbar",
                width = 0.3, 
                linewidth = 0.2,
                position = position_dodge(width = dodge_width)) +
  
  labs(y = "Mean Reaction Time", x = "Valence") +
  scale_x_discrete(labels = function(x) str_wrap(x, width = 10)) +
  theme(
    legend.position = "top",
    legend.direction = "horizontal",
    axis.title.x=element_blank(),
    text = element_text(family = "Helvetica"),
    axis.title.y = element_text(size = 16),     # x-axis title
    axis.text.y  = element_text(size = 12),     # y-axis ticks
    axis.text.x  = element_text(size = 12),     # x-axis ticks
  )



# ggsave("../graphs/total_rt_paper2.jpg",width = 6, height = 3)
# ggsave("../graphs/exp1_paper.pdf",width = 8, height = 4)
```

```{r}
length(sc[is.na(sc$Valence), ])
sc[is.na(sc$Valence), ]

print(unique(sc[is.na(sc$Valence), ]$ConceptualFoil))

```



## horizontal format
```{r}

names(sc)
agr <- sc %>%
    group_by(ConceptualFoil,Valence,Task,Word) %>%
    summarize(MeanReactionTime = mean(LogReactionTime), 
              CILow = ci.low(LogReactionTime), 
              CIHigh = ci.high(ReactionTime)) %>%
    mutate(YMin = MeanReactionTime - CILow, 
           YMax = MeanReactionTime + CIHigh)

agr$Task <- ifelse(agr$Task == "Valence", "Valence", "Conceptual")
agr$Task <- factor(agr$Task, levels = c("Conceptual","Valence"))

# Set dodge width to match violin grouping
dodge_width <- 0.9

ggplot(agr, aes(x = Valence, y = MeanReactionTime, fill = Task)) + 
  geom_violin(trim = FALSE, alpha = 0.4, position = position_dodge(width = dodge_width)) +
    facet_wrap(
      ~ConceptualFoil,
      ncol=4,
      labeller=label_wrap_gen(width=16)
      ) +
  # Add mean point with matching dodge
  stat_summary(fun = mean,
               geom = "point",
               shape = 23,
               size = 2,
               position = position_dodge(width = dodge_width)) +
  
  stat_summary(fun = median,
                geom = "crossbar",
                width = 0.3, 
                linewidth = 0.2,
                position = position_dodge(width = dodge_width)) +
  
  labs(y = "Mean Reaction Time", x = "Valence") +
  scale_x_discrete(labels = function(x) str_wrap(x, width = 10)) +
  theme(
    legend.position = "top",
    legend.direction = "horizontal",
    axis.title.x=element_blank(),
    text = element_text(family = "Helvetica"),
    axis.title.y = element_text(size = 16),     # x-axis title
    axis.text.y  = element_text(size = 12),     # y-axis ticks
    axis.text.x  = element_text(size = 12),     # x-axis ticks
  )



# ggsave("../graphs/total_rt_paper2.jpg",width = 6, height = 3)
# ggsave("../graphs/exp1_paper.pdf",width = 8, height = 4)
```

## Model

```{r}

```


# Similarity Judgment Experiments


```{r}

names(sj)
sj$ConceptualFoil <- as.factor(sj$ConceptualFoil)
agr <- sj %>%
  filter(FeatureMatch == "ValenceMatchingOnly") %>% 
    group_by(ConceptualFoil,Valence,WordPair) %>%
    summarize(MeanSimilarity = mean(SimilarityRating), 
              CILow = ci.low(SimilarityRating), 
              CIHigh = ci.high(SimilarityRating)) %>%
    mutate(YMin = MeanSimilarity - CILow, 
           YMax = MeanSimilarity + CIHigh)

# agr$Task <- ifelse(agr$Task == "Valence", "Valence", "Conceptual")
# agr$Task <- factor(agr$Task, levels = c("Conceptual","Valence"))

# Set dodge width to match violin grouping
dodge_width <- 0.9

ggplot(agr, aes(x = ConceptualFoil, y = MeanSimilarity, fill = Valence)) + 
  geom_violin(trim = FALSE, alpha = 0.4, position = position_dodge(width = dodge_width)) +
    # facet_wrap(
    #   ~ConceptualFoil,
    #   ncol=4,
    #   labeller=label_wrap_gen(width=16)
    #   ) +
  # Add mean point with matching dodge
  stat_summary(fun = mean,
               geom = "point",
               shape = 23,
               size = 2,
               position = position_dodge(width = dodge_width)) +
  
  stat_summary(fun = median,
                geom = "crossbar",
                width = 0.3, 
                linewidth = 0.2,
                position = position_dodge(width = dodge_width)) +
  
  labs(y = "Mean Similarity", x = "Valence") +
  scale_x_discrete(labels = function(x) str_wrap(x, width = 10)) +
  theme(
    legend.position = "top",
    legend.direction = "horizontal",
    axis.title.x=element_blank(),
    text = element_text(family = "Helvetica"),
    axis.title.y = element_text(size = 16),     # x-axis title
    axis.text.y  = element_text(size = 12),     # y-axis ticks
    axis.text.x  = element_text(size = 12),     # x-axis ticks
  )



# ggsave("../graphs/total_rt_paper2.jpg",width = 6, height = 3)

```


```{r}
sj$Valence <- as.factor(sj$Valence)
contrasts(sj$Valence)


names(sj)

center <- sj %>% 
  filter(FeatureMatch == "ValenceMatchingOnly") %>% 
  mutate(cValence = as.numeric(Valence)-mean(as.numeric(Valence)),
         WordPair = as.factor(WordPair),
         ID.true = as.factor(ID.true)
         ) %>% 
  drop_na()



m <- lmer(SimilarityRating ~ cValence*ConceptualFoil + (1|WordPair) + (1+cValence|ID.true), data = center)
summary(m)
  


```

