---
  title: "Everything"
author: "morgan moyer"
date: "`r Sys.Date()`"
output: html_document
---
  
```{r setup, include=FALSE, warning=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(lme4)
library(lmerTest)
library(multcomp) # not available for this version of R
library(stringr)
library(textstem)
library(tidyverse)
library(kableExtra)
theme_set(theme_bw())
library(ggrepel)
cbPalette <- c("#56B4E9", "#D55E00", "#009E73","#999999", "#E69F00")
this.dir <- dirname(rstudioapi::getSourceEditorContext()$path)
setwd(this.dir)
source("../../../helpers.R")

# v1 <- read_csv("../../01_verbs/exploratory_all_data/data/processed.csv")
# v1["Category"] <- "Verbs"

v <- read_csv("../../04_v1/data/processed.csv")
v["Category"] <- "Verbs"
v["Experiment"] <- "Ex1a: Conc-Abs (Verbs)"

n <- read_csv("../../05_n1/data/processed.csv")
n["Category"] <- "Nouns"
n["Experiment"] <- "Ex1b: Conc-Abs (Nouns)"

a <- read_csv("../../06_a1/data/processed.csv")
a["Category"] <- "Adjs"
a["Experiment"] <- "Ex1c: Conc-Abs (Adjs)"

a2 <- read_csv("../../07_a2/data/processed.csv")
a2["Category"] <- "Adjs"
a2["Experiment"] <- "Ex2b: Phys-Soc (Adjs)"


v2 <- read_csv("../../01_v2/data/processed.csv")
v2["Category"] <- "Verbs"
v2["Experiment"] <- "Ex2a: Phys-Psych (Verbs)"


n2 <- read_csv("../../02_n2/data/processed.csv")
n2["Category"] <- "Nouns"
n2["Experiment"] <- "Ex3: Animacy (Nouns)"

s <- read_csv("../../03_s/data/processed.csv")
s["Experiment"] <- "Ex4: Syntactic (N v. V)"

d <- bind_rows(v,n,a,a2,v2,n2,s)
nrow(d)
# sim <- read.csv("../data/total_similarity.csv")
# sim["WordPair"] <- paste(sim$Word1,sim$Word2,sep="-")
# sim <- sim[,c("WordPair","W2VSimilarity","BertSimilarity")]

# d <- merge(d,sim, by="WordPair")
nrow(d)
```


```{r}

agr <- d %>% 
  group_by(Experiment,FeatureMatch) %>% 
  reframe(MeanPropSimilar = mean(Response), 
          CILow = ci.low(Response), 
          CIHigh = ci.high(Response)) %>%
  mutate(YMin = MeanPropSimilar - CILow, 
         YMax = MeanPropSimilar + CIHigh)
# View(agr)

dodge = position_dodge(.9)
ggplot(data=agr, aes(x=reorder(FeatureMatch,MeanPropSimilar),y=MeanPropSimilar, fill=FeatureMatch)) +
  geom_bar(position=dodge,stat="identity") + 
  geom_errorbar(aes(ymin=YMin,ymax=YMax),width=.25,position=position_dodge(0.9)) +
  facet_wrap(~Experiment,ncol=4) +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank())

```


```{r}
names(d)
dcen <- d %>% 
  mutate(WordPair = as.factor(WordPair),
         ID.Ibex = as.factor(ID.Ibex),
         FeatureMatch = as.factor(FeatureMatch),
         cResponse = as.numeric(Response)-mean(as.numeric(Response)))

m <- lmer(cResponse ~ FeatureMatch + (1|WordPair) + (1+FeatureMatch|ID.Ibex), data = dcen)
summary(m)
```
